### ISSUE TITLE
Optional attributes in Dry::Data::Struct

### ISSUE THREAD

**Issue by jeromegn** [dryrb/dry-types#19]
Would it be possible to have optional attributes when using `Dry::Data::Struct`? When I try to instantiate an "incomplete" object, I get the strict hash `SchemaKey` error (well, the `StructError` since that's caught by the `Struct` class).

I might not be using this gem right, but some of my models are not "complete" sometimes and it doesn't matter (stuff is lazily loaded later when required.)

A more precise use-case: a `MongoDB::Collection` model has the attributes `:ns` (string) and `:count` (integer). However, sometimes we don't get the count right away due to the fact that it's an extra call to the database.

Would it be desirable to set `nil` on the attribute if that hash key is not present on instantiation? It would only work with the optional types, and so would be aligned with the basic premise of this gem.

**Comment by solnic** [comment]
An optional type means that *the value* can be nil, not the key in the hash can be skipped. I'm not sure how to solve this. I need to think about it a little bit and get back to you. Thanks for bringing this up.

BTW there's still some work to be done related to optional types, default-value types and hash schemas.

**Comment by jeromegn** [comment]
Ah yes, sorry, I didn't mean that I expected the behaviour.

My idea of how this could work would be: If a type is optional, when instantiating, if `!attributes.has_key?(schema_key)`, just assume `nil` as the value instead of throwing.

I imagine that might be a new schema constructor. Maybe it could be configured in the Dry::Data::Struct inheriting Class.

**Comment by jeromegn** [comment]
For now I have something like this defined in my app:

```ruby
module Dry
  module Data
    class Struct
      class Tolerant < Dry::Data::Struct
        def self.attributes(new_schema)
          prev_schema = schema || {}
          @schema = prev_schema.merge(new_schema)
          @constructor = Data['coercible.hash'].schema(schema)
          attr_reader(*(new_schema.keys - prev_schema.keys))
          self
        end
      end
    end
  end
end
```

with this line being of most interest:

```ruby
@constructor = Data['coercible.hash'].schema(schema)
```

I'm thinking adding a `Dry::Data::Struct.schema_type(type)` method where `type` might be `:strict` or `:tolerant` and then using that type when creating the constructor might be a nice. Or maybe it could follow the way the rest of the library seems to do it like:

```ruby
class User < Dry::Data::Struct.tolerant
```

**Comment by solnic** [comment]
Thanks for feedback. I'll get back to you on Monday, I'll be offline during the weekend.

**Comment by jodosha** [comment]
@solnic There are cases where we want to omit part of the schema. On top of my mind:

  * Unit tests (see example below)
  * Instantiate the entity with data coming from the database table, but selecting only a few keys. Instead  of `SELECT *` we do `SELECT name`.

Example:

```ruby
class User < Dry::Data::Struct
  attribute :name, Types::Maybe::Coercible::String
  attribute :x,    Types::Maybe::Coercible::String
  attribute :y,    Types::Maybe::Coercible::String
  attribute :z,    Types::Maybe::Coercible::String

  def foo
    # do something only with name
  end
end

# Unit test
it "does something great" do
  user = User.new({name: 'L'}) # It raises an error
  user.foo
end
```

If we have 10 attributes for that entity, it's tedious to have to specify all the keys just to instantiate it and unit test.

What do you think?

**Comment by solnic** [comment]
I'm OK with adding a different type of a struct that will use a hash schema which can fill in missing attributes and assign their default values. This is actually related to dry-validation too, where we can benefit from using types with default values.

**Comment by solnic** [comment]
I'm gonna experiment with a hash schema that will look if there's at least one default-value type, and if it exists, it's gonna use a special constructor that will set default values while constructing hash from the input. This will make structs with defaults working.

There's another thing I'm wondering about, which is using `required` and `optional` rather than just `attribute` to clearly specify what the expectation is. In case of `optional` we would fill in missing *keys* assuming they have types with default values. This would be much cleaner wrt intentions.

**Comment by pnomolos** [comment]
I would like to add a :+1: for this, but also indicate that I'm willing to help where help is necessary to get it up and running - my use case is in conjunction with https://github.com/apotonick/roar to parse incoming XML API calls to an Object.  Roar uses single-property assignment rather than hash assignment to make it happen, so I'm using `Virtus.model` for the time being :)

**Comment by solnic** [comment]
I'll add support for default values in hash schemas before next release. Hopefully next week.

**Comment by solnic** [comment]
OK I added support for default values in hash constructors and ability to set a different constructor type in structs, so ie this is possible now:

``` ruby
class User < Dry::Types::Struct
  constructor_type(:schema)

  attribute :name, Types::Strict::String
  attribute :admin, Types::Strict::Bool.default(true)
end

user = User.new(name: 'Jane')
user.admin # => true
```

However, I think this feature should not be used typically. Structs and Values are meant to be strict, you are constructing them from input that is supposed to be in valid state and have all the keys and values in place. For dealing with untrusted input it's better to use dry-validation's schemas.

Furthermore, if you need this just for testing, we can provide struct builders that can generate test data automatically.

I decided to add this feature just because I feel like it can help with adoption, personally I won't be using it.

**Comment by jodosha** [comment]
@solnic Thanks for adding this feature. IMO It helps to improve flexibility.

**Comment by dikond** [comment]
Thanks for adding this ability! Agree with solnic's comment above, it is useful for adoption...
